name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
      - name: Get Cmake
        uses: lukka/get-cmake@latest
      - name: list files
        run: ls